deploy_path: "/workspace/uniswap_v3_contract/deploy"
node_address: "http://localhost:8000"
hex_private_key: "0x37aa0f893d05914a4def0460c0a984d3611546cfb26924d7a7ca6e0db9950a2d"
hex_pub_address: "0x8ab0cf264df99d83525e9e11c7e4db01558ae1b1"
