apiVersion: 1

notifiers:
  # 邮件模板
  # - name: notification-email
  #   type: email
  #   uid: notification-email
  #   org_id: 1
  #   is_default: true
  #   settings:
  #     addresses: zzkouniya@163.com

  # tg模板
  # - name: notification-telegram
  #   type: telegram
  #   uid: notification-telegram
  #   org_id: 1
  #   is_default: false
  #   settings:
  #     bottoken: 1327880119:AAGDTagI5zmhO8lbkMxxxxxxxqop4KvAUTWlFR0VaUxxxx
  #     chatid: -409123128902xxx

  # 钉钉模板
  # - name: notification-dingding
  #   type: dingding
  #   uid: notifier-dingding
  #   org_id: 1
  #   is_default: false
  #   settings:
  #     url: https://oapi.dingtalk.com/robot/send?access_token=39b64875bcdxxxxxxxxxxxxae6473ad762d8f09683eaa938e4

  # webhook模板
  - name: notification-webhook
    type: webhook
    uid: notification-telegram
    org_id: 1
    is_default: false
    settings:
      url: http://47.56.233.149:4000/bot
      


      