apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  basicAuth: false
- name: Loki
  type: loki
  access: proxy
  url: http://muta-loki:3100
  basicAuth: false
  jsonData:
    maxLines: 100000000
  
- name: Prometheus-loki
  type: prometheus
  access: proxy
  url: http://muta-loki:3100/loki
  basicAuth: false
- name: jaeger
  type: jaeger
  access: proxy
  url: http://jaeger-query:16686
  basicAuth: false
