apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: stable-network-partition
  namespace: chaos-testing
spec:
  action: partition
  mode: fixed-percent
  value: 50
  selector:
    namespaces:
      - mutadev
    labelSelectors:
      chain: "muta"
      chaos: "true"
  direction: both
  duration: "30s"
  scheduler:
    cron: "@every 15m"
